#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-ExtUtils-Config
Version  : 0.007
Release  : 1
URL      : http://search.cpan.org/CPAN/authors/id/L/LE/LEONT/ExtUtils-Config-0.007.tar.gz
Source0  : http://search.cpan.org/CPAN/authors/id/L/LE/LEONT/ExtUtils-Config-0.007.tar.gz
Summary  : "A wrapper for perl's configuration"
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-ExtUtils-Config-doc

%description
This archive contains the distribution ExtUtils-Config,
version 0.007:
A wrapper for perl's configuration

%package doc
Summary: doc components for the perl-ExtUtils-Config package.
Group: Documentation

%description doc
doc components for the perl-ExtUtils-Config package.


%prep
%setup -q -n ExtUtils-Config-0.007

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/ExtUtils/Config.pm

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man3/*
