#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
# autospec version: v21
# autospec commit: 94c6be0
#
Name     : perl-ExtUtils-Config
Version  : 0.010
Release  : 43
URL      : https://cpan.metacpan.org/authors/id/L/LE/LEONT/ExtUtils-Config-0.010.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/L/LE/LEONT/ExtUtils-Config-0.010.tar.gz
Summary  : "A wrapper for perl's configuration"
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-ExtUtils-Config-license = %{version}-%{release}
Requires: perl-ExtUtils-Config-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
This archive contains the distribution ExtUtils-Config,
version 0.010:
A wrapper for perl's configuration

%package dev
Summary: dev components for the perl-ExtUtils-Config package.
Group: Development
Provides: perl-ExtUtils-Config-devel = %{version}-%{release}
Requires: perl-ExtUtils-Config = %{version}-%{release}

%description dev
dev components for the perl-ExtUtils-Config package.


%package license
Summary: license components for the perl-ExtUtils-Config package.
Group: Default

%description license
license components for the perl-ExtUtils-Config package.


%package perl
Summary: perl components for the perl-ExtUtils-Config package.
Group: Default
Requires: perl-ExtUtils-Config = %{version}-%{release}

%description perl
perl components for the perl-ExtUtils-Config package.


%prep
%setup -q -n ExtUtils-Config-0.010
cd %{_builddir}/ExtUtils-Config-0.010
pushd ..
cp -a ExtUtils-Config-0.010 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-ExtUtils-Config
cp %{_builddir}/ExtUtils-Config-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/perl-ExtUtils-Config/a8bcc41c8242633aef62bfe403d46899b7a41a66 || :
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*
## Remove excluded files
rm -f %{buildroot}*/usr/share/man/man3/version.3
rm -f %{buildroot}*/usr/share/man/man3/version::Internals.3
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/ExtUtils::Config.3
/usr/share/man/man3/ExtUtils::Config::MakeMaker.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-ExtUtils-Config/a8bcc41c8242633aef62bfe403d46899b7a41a66

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
